"""Changed tables

Revision ID: 057659b25b84
Revises: 
Create Date: 2020-05-27 17:45:37.794722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057659b25b84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_name', sa.String(length=80), nullable=False),
    sa.Column('student_one', sa.String(length=80), nullable=False),
    sa.Column('student_two', sa.String(length=80), nullable=False),
    sa.Column('student_three', sa.String(length=80), nullable=False),
    sa.Column('student_four', sa.String(length=80), nullable=False),
    sa.Column('student_five', sa.String(length=80), nullable=False),
    sa.Column('student_six', sa.String(length=80), nullable=False),
    sa.Column('student_seven', sa.String(length=80), nullable=False),
    sa.Column('student_eight', sa.String(length=80), nullable=False),
    sa.Column('student_nine', sa.String(length=80), nullable=False),
    sa.Column('student_ten', sa.String(length=80), nullable=False),
    sa.Column('student_eleven', sa.String(length=80), nullable=False),
    sa.Column('student_twelve', sa.String(length=80), nullable=False),
    sa.Column('student_thirteen', sa.String(length=80), nullable=False),
    sa.Column('student_fourteen', sa.String(length=80), nullable=False),
    sa.Column('student_fifteen', sa.String(length=80), nullable=False),
    sa.Column('student_sixteen', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_cohort_name'), 'cohort', ['cohort_name'], unique=True)
    op.create_table('pairing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('pair_one', sa.String(length=80), nullable=False),
    sa.Column('pair_two', sa.String(length=80), nullable=False),
    sa.Column('pair_three', sa.String(length=80), nullable=False),
    sa.Column('pair_four', sa.String(length=80), nullable=False),
    sa.Column('pair_five', sa.String(length=80), nullable=False),
    sa.Column('pair_six', sa.String(length=80), nullable=False),
    sa.Column('pair_seven', sa.String(length=80), nullable=False),
    sa.Column('pair_eight', sa.String(length=80), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairing_date'), 'pairing', ['date'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pairing_date'), table_name='pairing')
    op.drop_table('pairing')
    op.drop_index(op.f('ix_cohort_cohort_name'), table_name='cohort')
    op.drop_table('cohort')
    # ### end Alembic commands ###
