"""initalising pairing table

Revision ID: b9e8aea13132
Revises: 
Create Date: 2020-05-26 16:02:50.583217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e8aea13132'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('pair_one', sa.String(length=80), nullable=False),
    sa.Column('pair_two', sa.String(length=80), nullable=False),
    sa.Column('pair_three', sa.String(length=80), nullable=False),
    sa.Column('pair_four', sa.String(length=80), nullable=False),
    sa.Column('pair_five', sa.String(length=80), nullable=False),
    sa.Column('pair_six', sa.String(length=80), nullable=False),
    sa.Column('pair_seven', sa.String(length=80), nullable=False),
    sa.Column('pair_eight', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairing_date'), 'pairing', ['date'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pairing_date'), table_name='pairing')
    op.drop_table('pairing')
    # ### end Alembic commands ###
